@startuml TRACEX_CasosDeUso

skinparam actorStyle hollow
skinparam packageStyle rectangle

skinparam usecase {
  BackgroundColor #EEF5FF
  BorderColor #3A7BD5
  ArrowColor #3A7BD5
}
skinparam actor {
  BackgroundColor #D5E8D4 
  BorderColor #82B366
}

title Diagrama de Casos de Uso

' ─── ACTORES ───────────────────────────────────────────
actor "Cliente / Remitente" as Cliente
actor "Destinatario"        as Destinatario
actor "Operador Logístico"  as Operador
actor "Repartidor"          as Repartidor
actor "Supervisor"          as Supervisor
actor "Timer"       as Timer

' ─── SISTEMA ────────────────────────────────────────────
rectangle "TRACEX — Sistema de Seguimiento de Envíos" {

  ' --- Gestión de envíos (Cliente) ---
  usecase "Solicitar envío"                  as UC1
  usecase "Realizar pago"                    as UC1b
  usecase "Consultar seguimiento de envío"   as UC2

  ' --- Ciclo logístico (Operador) ---
  usecase "Registrar evento logístico\n(escaneo de paquete)" as UC3
  usecase "Recepcionar paquete" as UC3a

  ' --- Entrega (Repartidor) ---
  usecase "Registrar entrega"        as UC4
  usecase "Registrar intento fallido"        as UC5
  usecase "Iniciar proceso de devolución"    as UC7

  ' --- Administración ---
  usecase "Generar informe de jornada"       as UC8
  usecase "Habilitar empleado" as UC9

  usecase "Iniciar Sesion" as UC10
}

' ─── RELACIONES ACTOR ↔ CASO DE USO ─────────────────────
Supervisor   --|> Operador
Supervisor   --> UC9

Cliente      --> UC2

Destinatario --> UC2

Operador     --> UC3
Operador     --> UC3a
Operador     --> UC1
Operador     --> UC10

Repartidor   --> UC4
Repartidor   --> UC5
Repartidor   --> UC10

Timer        --> UC8


' ─── RELACIONES ENTRE CASOS DE USO ──────────────────────
UC1 ..> UC1b : <<include>>

UC3 ..> UC2 : <<include>>

UC5 <.. UC7  : <<extend>>

@enduml