@startuml   
skinparam classAttributeIconSize 0
' --- CLASES ---
class Envio {
  - codigoSeguimiento: String
  - importeTotal: double
}

class Paquete {
  - peso: float
  - dimensiones: String
}

class Cliente {
  - DNI: String
  - nombre: String
  - apellido: String
  - telefono: String
  - direccion: String
}

class Empleado {
  - legajo: String
  - nombre: String
  - apellido: String
}

class TipoEmpleado {
  - idTipoEmpleado: int
  - descripcion: String
}

class Zona {
  - idZona: int
  - descripcion: String
}

class TipoServicio {
  - idTipo: int
  - descripcion: String
}

class Pago {
  - nroPago: int
  - monto: double
  - fecha: Date
}

class RegistroSeguimiento {
  - fecha: Date
  - hora: Time
  - ubicacion: String
}

class Estado {
  - descripcion: String
}

class IntentoEntrega {
  - fecha: Date
  - hora: Time
  - resultado: String
}

' --- RELACIONES DEL SISTEMA ---

' El Cliente y sus roles 
Envio "*" -- "1" Cliente : + remitente
Envio "*" -- "1" Cliente : + destinatario

' El Envío y su contenido físico
Envio "1" -- "1" Paquete : contiene

' Factores para el cálculo del precio del envío
Envio "*" -- "1" Zona : corresponde
Envio "*" -- "1" TipoServicio : requiere

' El pago
Envio "1" -- "1" Pago : posee

' El historial de escaneos referidos al paquete
Paquete "1" -- "*" RegistroSeguimiento : tiene
RegistroSeguimiento "*" -- "1" Estado : indica
RegistroSeguimiento "*" -- "1" Empleado : registrado por

' Los intentos de entrega del Envío
Envio "1" -- "0..2" IntentoEntrega : tiene
IntentoEntrega "*" -- "1" Empleado : corresponde

' El empleado, su tipo y su zona
Empleado "*" -- "1" TipoEmpleado : es un
Empleado "*" -- "1" Zona : asignado a

' --- NOTAS ---
note bottom of Cliente #cbe7cd
  **Justificación de Diseño:**
  La clase Cliente representa tanto a remitentes
  como a destinatarios. 
  Se modela con dos asociaciones simples
  indicando los roles,
  evitando herencia innecesaria ya que
  estructuralmente no poseen atributos distintos,
  manteniendo Alta Cohesión.
end note

note bottom of Estado #d1c4db
  **Los estados posibles que puede tomar un paquete son:**
  - Clasificación
  - Transporte 
  - Distribución
  - Entregado
  - Intento Fallido
  - En proceso de devolución
end note

note bottom of TipoServicio #d1c4db
**Los distintos tipos de servicio son:**
  - Estándar
  - Urgente
  - Exprés
end note
@enduml