@startuml

 class Tarifa{
    - id: Long
    - descripcion: String
    - importe: Double
    + calcularImporte(paquete: Paquete,tipoServicio: TipoServicio, idZona : Long ): Double
  }

  class TipoServicio{
    - id: Long
    - descripcion: String
    - importe: Double
    + calcularImporte(tipo: TipoDeServicio, zona: Zona): Double
    + calcularDescuento(importeBase: Double): Double
  }

  class Paquete {
    - id: Long
    - peso: Double
    - alto: Double
    - ancho: Double
    - largo: Double
    - descripcion: String
    + Paquete(peso: Double, alto: Double, ancho: Double, largo: Double, descripcion: String)
    + calcularVolumen(): Double
    + getPeso(): Double
    + esValido(): Boolean
  }

  class Zona {
    - id: Long
    - nombre: String
    - codigoPostal: String
    - costoEnvio: Double
    + getCostoEnvio(): Double
    + buscarZona(idZona: Long) : Zona
  }

  class TipoPaquete{
    - id: Long
    - descripcion: String
    - dimensionesMaximas: String
    - pesoMaximo: Double
    - costo: Double
    + calcularCosto(paquete: Paquete): Double
  }

    class Envio {
    - id: Long
    - codigoSeguimiento: String
    - importe: Double
    - estadoActual: EstadoEnvio
    
    + Envio(remitente: Cliente, destinatario: Cliente, paquete: Paquete, tipo: TipoServicio)
    + confirmarPago(pago: Pago): Boolean
    + registrarEvento(estado: EstadoEnvio, empleado: Empleado, sucursal: Sucursal, desc: String): void
    + asignarImporte(importe: Double) : Boolean
    + registrarIntentoFallido(motivo: String, empleado: Empleado, numeroIntento: Integer): IntentoEntrega
    + generarCodigoSeguimiento(): String
    + getEstadoActual(): EstadoEnvio
    + agregarEvento(evento : EventoLogistico) : void
  }

  Tarifa "*" .down.> "1" Zona : aplica >
Tarifa "*" .down.> "1" TipoServicio : aplica >
Tarifa "1" .down.> "1" Paquete : aplica >
Tarifa "1" .down.> "1" Envio : asigna >
Tarifa "1" .down.> "1" TipoPaquete : asigna >

@enduml